### ISSUE TITLE
russian encoding

### ISSUE THREAD

**Issue by prizrak-andy** [OsipovDV/1c_update#1]
полетела кодировка комментариев.

**Comment by OsipovDV** [comment]
она не полетела, там 1251 ее гит не понимает.

**Comment by prizrak-andy** [comment]
ну вероятно нужен utf, без комментариев слабочитаемо. можно конечно и перекодировщик написать, но нужно-ли ?

**Comment by OsipovDV** [comment]
перекодировал, если что-то пропустил, просьба прислать номер строки

**Comment by prizrak-andy** [comment]
премного благодарен
